import { Routes } from '@angular/router';
import { AuthGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'blog', loadComponent: () => import('./pages/blog/blog-list.component').then(m => m.BlogListComponent) },
  { path: 'blog/:slug', loadComponent: () => import('./pages/blog/blog-detail.component').then(m => m.BlogDetailComponent) },
  { path: 'contact', loadComponent: () => import('./pages/contact/contact.component').then(m => m.ContactComponent) },
  { path: 'aboutus', loadComponent: () => import('./pages/landing/aboutus/aboutus.component').then(m => m.AboutusComponent) },
  { path: 'aesthetic-dentistry-india-medical-tourism', loadComponent: () => import('./pages/landing/aesthetic-dentistry-india-medical-tourism/aesthetic-dentistry-india-medical-tourism.component').then(m => m.AestheticDentistryIndiaMedicalTourismComponent) },
  { path: 'allied-healthcare-india-medical-tourism', loadComponent: () => import('./pages/landing/allied-healthcare-india-medical-tourism/allied-healthcare-india-medical-tourism.component').then(m => m.AlliedHealthcareIndiaMedicalTourismComponent) },
  { path: 'bariatric-surgery-india-medical-tourism', loadComponent: () => import('./pages/landing/bariatric-surgery-india-medical-tourism/bariatric-surgery-india-medical-tourism.component').then(m => m.BariatricSurgeryIndiaMedicalTourismComponent) },
  { path: 'cardiac-surgery-india-medical-tourism', loadComponent: () => import('./pages/landing/cardiac-surgery-india-medical-tourism/cardiac-surgery-india-medical-tourism.component').then(m => m.CardiacSurgeryIndiaMedicalTourismComponent) },
  { path: 'cosmetic-and-plastic-surgery-india-medical-tourism', loadComponent: () => import('./pages/landing/cosmetic-and-plastic-surgery-india-medical-tourism/cosmetic-and-plastic-surgery-india-medical-tourism.component').then(m => m.CosmeticAndPlasticSurgeryIndiaMedicalTourismComponent) },
  { path: 'demo-geriatric', loadComponent: () => import('./pages/landing/demo-geriatric/demo-geriatric.component').then(m => m.DemoGeriatricComponent) },
  { path: 'dermatology-and-aesthetics-india-medical-tourism', loadComponent: () => import('./pages/landing/dermatology-and-aesthetics-india-medical-tourism/dermatology-and-aesthetics-india-medical-tourism.component').then(m => m.DermatologyAndAestheticsIndiaMedicalTourismComponent) },
  { path: 'diabetes-management-india-medical-tourism', loadComponent: () => import('./pages/landing/diabetes-management-india-medical-tourism/diabetes-management-india-medical-tourism.component').then(m => m.DiabetesManagementIndiaMedicalTourismComponent) },
  { path: 'download', loadComponent: () => import('./pages/landing/download/download.component').then(m => m.DownloadComponent) },
  { path: 'elder-care', loadComponent: () => import('./pages/landing/elder-care/elder-care.component').then(m => m.ElderCareComponent) },
  { path: 'elder-care2', loadComponent: () => import('./pages/landing/elder-care2/elder-care2.component').then(m => m.ElderCare2Component) },
  { path: 'elder-care3', loadComponent: () => import('./pages/landing/elder-care3/elder-care3.component').then(m => m.ElderCare3Component) },
  { path: 'emergency-medical-assistance-india-medical-tourism', loadComponent: () => import('./pages/landing/emergency-medical-assistance-india-medical-tourism/emergency-medical-assistance-india-medical-tourism.component').then(m => m.EmergencyMedicalAssistanceIndiaMedicalTourismComponent) },
  { path: 'ent-care-india-medical-tourism', loadComponent: () => import('./pages/landing/ent-care-india-medical-tourism/ent-care-india-medical-tourism.component').then(m => m.EntCareIndiaMedicalTourismComponent) },
  { path: 'fertility-treatments-india-medical-tourism', loadComponent: () => import('./pages/landing/fertility-treatments-india-medical-tourism/fertility-treatments-india-medical-tourism.component').then(m => m.FertilityTreatmentsIndiaMedicalTourismComponent) },
  { path: 'gallery', loadComponent: () => import('./pages/landing/gallery/gallery.component').then(m => m.GalleryComponent) },
  { path: 'gastrointestinal-procedures-india-medical-tourism', loadComponent: () => import('./pages/landing/gastrointestinal-procedures-india-medical-tourism/gastrointestinal-procedures-india-medical-tourism.component').then(m => m.GastrointestinalProceduresIndiaMedicalTourismComponent) },
  { path: 'gc-faq', loadComponent: () => import('./pages/landing/gc-faq/gc-faq.component').then(m => m.GcFaqComponent) },
  { path: 'gctermandcondition', loadComponent: () => import('./pages/landing/gctermandcondition/gctermandcondition.component').then(m => m.GctermandconditionComponent) },
  { path: 'genomic-medicine-india-medical-tourism', loadComponent: () => import('./pages/landing/genomic-medicine-india-medical-tourism/genomic-medicine-india-medical-tourism.component').then(m => m.GenomicMedicineIndiaMedicalTourismComponent) },
  { path: 'geriatric-care-india-medical-tourism', loadComponent: () => import('./pages/landing/geriatric-care-india-medical-tourism/geriatric-care-india-medical-tourism.component').then(m => m.GeriatricCareIndiaMedicalTourismComponent) },
  { path: 'geriatric', loadComponent: () => import('./pages/landing/geriatric/geriatric.component').then(m => m.GeriatricComponent) },
  { path: 'home', loadComponent: () => import('./pages/landing/home/home.component').then(m => m.HomeComponent) },
  { path: 'mental-health-and-wellness-india-medical-tourism', loadComponent: () => import('./pages/landing/mental-health-and-wellness-india-medical-tourism/mental-health-and-wellness-india-medical-tourism.component').then(m => m.MentalHealthAndWellnessIndiaMedicalTourismComponent) },
  { path: 'mt-faq', loadComponent: () => import('./pages/landing/mt-faq/mt-faq.component').then(m => m.MtFaqComponent) },
  { path: 'mts', loadComponent: () => import('./pages/landing/mts/mts.component').then(m => m.MtsComponent) },
  { path: 'mttermandcondition', loadComponent: () => import('./pages/landing/mttermandcondition/mttermandcondition.component').then(m => m.MttermandconditionComponent) },
  { path: 'neonatal-care-india-medical-tourism', loadComponent: () => import('./pages/landing/neonatal-care-india-medical-tourism/neonatal-care-india-medical-tourism.component').then(m => m.NeonatalCareIndiaMedicalTourismComponent) },
  { path: 'neurosurgery-india-medical-tourism', loadComponent: () => import('./pages/landing/neurosurgery-india-medical-tourism/neurosurgery-india-medical-tourism.component').then(m => m.NeurosurgeryIndiaMedicalTourismComponent) },
  { path: 'ophthalmology-india-medical-tourism', loadComponent: () => import('./pages/landing/ophthalmology-india-medical-tourism/ophthalmology-india-medical-tourism.component').then(m => m.OphthalmologyIndiaMedicalTourismComponent) },
  { path: 'organ-transplants-india-medical-tourism', loadComponent: () => import('./pages/landing/organ-transplants-india-medical-tourism/organ-transplants-india-medical-tourism.component').then(m => m.OrganTransplantsIndiaMedicalTourismComponent) },
  { path: 'orthopedic-surgery-india-medical-tourism', loadComponent: () => import('./pages/landing/orthopedic-surgery-india-medical-tourism/orthopedic-surgery-india-medical-tourism.component').then(m => m.OrthopedicSurgeryIndiaMedicalTourismComponent) },
  { path: 'pain-management-india-medical-tourism', loadComponent: () => import('./pages/landing/pain-management-india-medical-tourism/pain-management-india-medical-tourism.component').then(m => m.PainManagementIndiaMedicalTourismComponent) },
  { path: 'palliative-care-india-medical-tourism', loadComponent: () => import('./pages/landing/palliative-care-india-medical-tourism/palliative-care-india-medical-tourism.component').then(m => m.PalliativeCareIndiaMedicalTourismComponent) },
  { path: 'pediatric-care-india-medical-tourism', loadComponent: () => import('./pages/landing/pediatric-care-india-medical-tourism/pediatric-care-india-medical-tourism.component').then(m => m.PediatricCareIndiaMedicalTourismComponent) },
  { path: 'plastic-and-reconstructive-india-medical-tourism', loadComponent: () => import('./pages/landing/plastic-and-reconstructive-india-medical-tourism/plastic-and-reconstructive-india-medical-tourism.component').then(m => m.PlasticAndReconstructiveIndiaMedicalTourismComponent) },
  { path: 'pulmonology-india-medical-tourism', loadComponent: () => import('./pages/landing/pulmonology-india-medical-tourism/pulmonology-india-medical-tourism.component').then(m => m.PulmonologyIndiaMedicalTourismComponent) },
  { path: 'rehabilitation-services-india-medical-tourism', loadComponent: () => import('./pages/landing/rehabilitation-services-india-medical-tourism/rehabilitation-services-india-medical-tourism.component').then(m => m.RehabilitationServicesIndiaMedicalTourismComponent) },
  { path: 'rheumatology-india-medical-tourism', loadComponent: () => import('./pages/landing/rheumatology-india-medical-tourism/rheumatology-india-medical-tourism.component').then(m => m.RheumatologyIndiaMedicalTourismComponent) },
  { path: 'robotic-surgery-india-medical-tourism', loadComponent: () => import('./pages/landing/robotic-surgery-india-medical-tourism/robotic-surgery-india-medical-tourism.component').then(m => m.RoboticSurgeryIndiaMedicalTourismComponent) },
  { path: 'stem-cell-therapy-india-medical-tourism', loadComponent: () => import('./pages/landing/stem-cell-therapy-india-medical-tourism/stem-cell-therapy-india-medical-tourism.component').then(m => m.StemCellTherapyIndiaMedicalTourismComponent) },
  { path: 'telemedicine-services-india-medical-tourism', loadComponent: () => import('./pages/landing/telemedicine-services-india-medical-tourism/telemedicine-services-india-medical-tourism.component').then(m => m.TelemedicineServicesIndiaMedicalTourismComponent) },
  { path: 'termandcondition', loadComponent: () => import('./pages/landing/termandcondition/termandcondition.component').then(m => m.TermandconditionComponent) },
  { path: 'transgender-healthcare-india-medical-tourism', loadComponent: () => import('./pages/landing/transgender-healthcare-india-medical-tourism/transgender-healthcare-india-medical-tourism.component').then(m => m.TransgenderHealthcareIndiaMedicalTourismComponent) },
  { path: 'travelers-health-clinic-india-medical-tourism', loadComponent: () => import('./pages/landing/travelers-health-clinic-india-medical-tourism/travelers-health-clinic-india-medical-tourism.component').then(m => m.TravelersHealthClinicIndiaMedicalTourismComponent) },
  { path: 'urology-services-india-medical-tourism', loadComponent: () => import('./pages/landing/urology-services-india-medical-tourism/urology-services-india-medical-tourism.component').then(m => m.UrologyServicesIndiaMedicalTourismComponent) },
  { path: 'addressing-common-concerns-and-misconceptions', loadComponent: () => import('./pages/landing/addressing_common_concerns_and_misconceptions/addressing_common_concerns_and_misconceptions.component').then(m => m.AddressingCommonConcernsAndMisconceptionsComponent) },
  { path: 'navigating-the-landscape-of-indian-medical-tourism', loadComponent: () => import('./pages/landing/navigating_the_landscape_of_indian_medical_tourism/navigating_the_landscape_of_indian_medical_tourism.component').then(m => m.NavigatingTheLandscapeOfIndianMedicalTourismComponent) },
  { path: 'transformational-jour-neys-and-outcomes', loadComponent: () => import('./pages/landing/transformational_jour_neys_and_outcomes/transformational_jour_neys_and_outcomes.component').then(m => m.TransformationalJourNeysAndOutcomesComponent) },
  {path: 'admin-login', loadComponent: ()=> import('./admin/login/login.component').then(m=>m.LoginComponent)},
  {path: 'admin-dashboard', loadComponent: ()=> import('./admin/dashboard/dashboard.component').then(m=>m.DashboardComponent), canActivate: [AuthGuard]},
  { path: 'checkout', loadComponent: () => import('./pages/landing/checkout/checkout.component').then(m => m.CheckoutComponent) },
  { path: '**', loadComponent: () => import('./pages/not-found/not-found.component').then(m => m.NotFoundComponent) }
];
